[build-system]
build-backend = "hatchling.build"
requires = [
    "semiwrap", "hatch-meson", "hatch-vcs", "hatchling",
    "native.wpiutil==2025.3.2",
]

[project]
name = "robotpy-wpiutil"
dynamic = ["version"]
description = "Binary wrapper for FRC WPIUtil library"
authors = [
    {name = "RobotPy Development Team", email = "robotpy@googlegroups.com"},
]
license = "BSD-3-Clause"
install_requires = [
    "native.wpiutil==2025.3.2",
    "msvc-runtime>=14.42.34433; platform_system == 'Windows'"
]

[project.urls]
"Source code" = "https://github.com/robotpy/mostrobotpy"

[tool.hatch.version]
source = "vcs"
raw-options.root = "../.."

[tool.hatch.build.hooks.vcs]
version-file = "wpiutil/version.py"



[tool.hatch.build.hooks.semiwrap]
# update_init = [
#     "wpiutil",
#     "wpiutil.log wpiutil._wpiutil.log",
#     "wpiutil.sync wpiutil._wpiutil.sync",
#     "wpiutil.wpistruct wpiutil._wpiutil.wpistruct",
# ]
# scan_headers_ignore = [
#     "fmt/*",
#     "google/*",
#     "wpi/*",
#     "wpystruct_fns.h",
#     "pb.h",
#     "pb_common.h",
#     "pb_decode.h",
#     "pb_encode.h",
# ]

[tool.hatch.build.hooks.meson]


[tool.semiwrap]
[tool.semiwrap.extension_modules."wpiutil._wpiutil"]
name = "wpiutil"
includes = [
    "wpiutil/src/wpistruct",
]
wraps = ["native.wpiutil"]
depends = ["wpiutil-casters"]

[tool.semiwrap.extension_modules."wpiutil._wpiutil".headers]
# wpi
DataLog = "wpi/DataLog.h"
DataLogReader = "wpi/DataLogReader.h"
DataLogBackgroundWriter = "wpi/DataLogBackgroundWriter.h"
DataLogWriter = "wpi/DataLogWriter.h"
StackTrace = "wpi/StackTrace.h"
Synchronization = "wpi/Synchronization.h"
RawFrame = "wpi/RawFrame.h"

# wpi/sendable
Sendable = "wpi/sendable/Sendable.h"
SendableBuilder = "wpi/sendable/SendableBuilder.h"
#SendableHelper = "wpi/sendable/SendableHelper.h"
SendableRegistry = "wpi/sendable/SendableRegistry.h"

WPyStruct = "src/wpistruct/wpystruct_fns.h"

[tool.semiwrap.export_type_casters.wpiutil-casters]
pypackage = "wpiutil"
includedir = [
    "wpiutil/src/type_casters",
    "wpiutil/src/wpistruct",
]

[[tool.semiwrap.export_type_casters.wpiutil-casters.headers]]
header = "wpi_array_type_caster.h"
types = ["wpi::array"]

[[tool.semiwrap.export_type_casters.wpiutil-casters.headers]]
header = "wpi_json_type_caster.h"
types = ["wpi::json"]

[[tool.semiwrap.export_type_casters.wpiutil-casters.headers]]
header = "wpi_span_type_caster.h"
types = ["std::span"]

[[tool.semiwrap.export_type_casters.wpiutil-casters.headers]]
header = "wpi_smallset_type_caster.h"
types = ["wpi::SmallSet"]

[[tool.semiwrap.export_type_casters.wpiutil-casters.headers]]
header = "wpi_smallvector_type_caster.h"
types = ["wpi::SmallVector"]

[[tool.semiwrap.export_type_casters.wpiutil-casters.headers]]
header = "wpi_smallvectorimpl_type_caster.h"
types = ["wpi::SmallVectorImpl"]

[[tool.semiwrap.export_type_casters.wpiutil-casters.headers]]
header = "wpi_string_map_caster.h"
types = ["wpi::StringMap"]

[[tool.semiwrap.export_type_casters.wpiutil-casters.headers]]
header = "wpi_ct_string_type_caster.h"
types = ["wpi::ct_string"]

[[tool.semiwrap.export_type_casters.wpiutil-casters.headers]]
header = "wpystruct.h"
types = ["WPyStruct"]
