---
name: cross

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to build'
        required: true
        default: 'good_version'


concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  cross-meson:
    runs-on: ubuntu-24.04
    strategy:
      max-parallel: ${{ fromJSON(needs.setup_concurrency.outputs.max-parallel).v }}
      matrix:
        os:
        - container: wpilib/raspbian-cross-ubuntu:2025-bookworm-24.04-py311
          name: raspbian-py311
        - container: wpilib/raspbian-cross-ubuntu:2025-bookworm-24.04-py312
          name: raspbian-py312
        - container: wpilib/raspbian-cross-ubuntu:2025-bookworm-24.04-py313
          name: raspbian-py313

    container:
      image: "${{ matrix.os.container }}"

    steps:
    - name: Normalize ref
      id: ref
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          # strip refs/tags/ to get tag name
          echo "ref_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "ref_name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
        fi

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ steps.ref.outputs.ref_name }}

    - name: Setup cross environment for meson
      uses: robotpy/build-actions/setup-cross-meson@semiwrap

    - run: apt-get update
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ matrix.os.container }}
        variant: ccache

    - name: Install deps
      shell: bash
      run: |
        /build/venv/bin/cross-pip --disable-pip-version-check install -r rdev_requirements.txt

    - name: Build wheels
      shell: bash
      run: |
        /build/venv/bin/cross-python -m devtools ci build-meson-wheels --no-test --cross=cross.txt

    - uses: actions/upload-artifact@v4
      with:
        name: cross-meson-${{ matrix.os.name }}
        path: dist
